# Generated by Django 6.0.4 on 2026-04-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentreport',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'incident report', 'verbose_name_plural': 'incident reports'},
        ),
    ]
